project:
  type: website
  output-dir: docs  # Para GitHub Pages

website:
  title: "Yuri | Meu Blog"
  description: "Meu espaço de tecnologia, dados e projetos."
  navbar:
    background: "#001f3f"  # Azul escuro no menu
    left:
      - text: "Início"
        href: index.qmd
      - text: "Projetos"
        href: projetos.qmd
      - text: "Sobre"
        href: sobre.qmd
      - text: "Posts"
        href: posts/primeiro-post.qmd

  page-footer:
    background: "#001f3f"
    left: "© 2025 Yuri"
    right: 
      - icon: github
        href: https://github.com/Yuricostalima
      - icon: linkedin
        href: https://www.linkedin.com/in/yuricostalima/
      - icon: globe
        href: https://yuricostalima.github.io/my-personal-blog/
      - icon: whatsapp
        href: https://wa.me/5585999259876?text=Olá%20Yuri!%20Vi%20seu%20blog%20e%20gostaria%20de%20conversar%20sobre%20sua%20jornada%20em%20tecnologia.
format:
  html:
    theme: cyborg  # Base dark (lembrando que podemos usar também darkly ou slate)
    css: styles.css
    toc: true