project:
  type: website
  output-dir: docs  # Para GitHub Pages

website:
  title: "Yuri | Meu Blog"
  description: "Meu espaço de tecnologia, dados e projetos."
  navbar:
    background: "#1E1E1E"
    left:
      - text: "Início"
        href: index.qmd

      - text: "Dashboards | BI"
        href: dashboards.qmd
      - text: "Labs | AWS"
        href: labsAWSTutoriaisPraticos.qmd
      - text: "Engenharia"
        href: engenhariaDeDados.qmd
      
      - text: "Sobre"
        href: sobre.qmd

  page-footer:
    background: "#1E1E1E"
    center:  # Adicione esta seção para centralizar
      - icon: github
        href: https://github.com/Yuricostalima
      - icon: linkedin
        href: https://www.linkedin.com/in/yuricostalima/
      - icon: whatsapp
        href: https://wa.me/5585999259876?text=Olá%20Yuri!%20Vi%20seu%20blog%20e%20gostaria%20de%20conversar%20sobre%20sua%20jornada%20em%20tecnologia.
      - icon: envelope
        href: https://mailto:yuricosta8675@gmail.com/
    left: "© 2025 Yuri"
    right: []  # Deixe vazio para não aparecer nada à direita

format:
  html:
    theme: cyborg
    css: styles.css
    toc: true